fmt:
	terraform fmt -recursive ./src

init:
	cd src && terraform init

plan:
	cd src && terraform plan

apply:
	cd src && terraform apply -auto-approve

destroy:
	cd src && terraform destroy -auto-approve
